# Example Predictor: Linear Rollout Predictor

This example contains basic functionality for training and evaluating a linear predictor that rolls out predictions day-by-day.

First, a training data set is created from historical case and npi data.

Second, a linear model is trained to predict future cases from prior case data along with prior and future npi data.
The model is an off-the-shelf sklearn Lasso model, that uses a positive weight constraint to enforce the assumption that increased npis has a negative correlation with future cases.

Third, a sample evaluation set is created, and the predictor is applied to this evaluation set to produce prediction results in the correct format.

## Training

In [1]:
import pickle
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split

### Copy the data locally

In [2]:
# Main source for the training data
DATA_URL = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv'
# Local file
DATA_FILE = 'data/OxCGRT_latest.csv'

In [3]:
import os
import urllib.request
if not os.path.exists('data'):
    os.mkdir('data')
urllib.request.urlretrieve(DATA_URL, DATA_FILE)

('data/OxCGRT_latest.csv', <http.client.HTTPMessage at 0x7f440eee6a50>)

In [4]:
# Load historical data from local file
df = pd.read_csv(DATA_FILE, 
                 parse_dates=['Date'],
                 encoding="ISO-8859-1",
                 dtype={"RegionName": str,
                        "RegionCode": str},
                 error_bad_lines=False)

In [5]:
df.columns

Index(['CountryName', 'CountryCode', 'RegionName', 'RegionCode',
       'Jurisdiction', 'Date', 'C1_School closing', 'C1_Flag',
       'C2_Workplace closing', 'C2_Flag', 'C3_Cancel public events', 'C3_Flag',
       'C4_Restrictions on gatherings', 'C4_Flag', 'C5_Close public transport',
       'C5_Flag', 'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'H6_Facial Coverings', 'H6_Flag', 'H7_Vaccination policy', 'H7_Flag',
       'M1_Wildcard', 'ConfirmedCases', 'ConfirmedDeaths', 'StringencyIndex',
       'StringencyIndexForDisplay', 'StringencyLegacyIndex',
       'StringencyLegacyIndexForDispla

In [6]:
# For testing, restrict training data to that before a hypothetical predictor submission date
HYPOTHETICAL_SUBMISSION_DATE = np.datetime64("2020-07-31")
df = df[df.Date <= HYPOTHETICAL_SUBMISSION_DATE]

In [7]:
# Add RegionID column that combines CountryName and RegionName for easier manipulation of data
df['GeoID'] = df['CountryName'] + '__' + df['RegionName'].astype(str)

In [8]:
# Add new cases column
df['NewCases'] = df.groupby('GeoID').ConfirmedCases.diff().fillna(0)

In [9]:
# Keep only columns of interest
id_cols = ['CountryName',
           'RegionName',
           'GeoID',
           'Date']
cases_col = ['NewCases']
npi_cols = ['C1_School closing',
            'C2_Workplace closing',
            'C3_Cancel public events',
            'C4_Restrictions on gatherings',
            'C5_Close public transport',
            'C6_Stay at home requirements',
            'C7_Restrictions on internal movement',
            'C8_International travel controls',
            'H1_Public information campaigns',
            'H2_Testing policy',
            'H3_Contact tracing',
            'H6_Facial Coverings']
df = df[id_cols + cases_col + npi_cols]

In [10]:
# Fill any missing case values by interpolation and setting NaNs to 0
df.update(df.groupby('GeoID').NewCases.apply(
    lambda group: group.interpolate()).fillna(0))

In [11]:
# Fill any missing NPIs by assuming they are the same as previous day
for npi_col in npi_cols:
    df.update(df.groupby('GeoID')[npi_col].ffill().fillna(0))

In [12]:
df

CountryName RegionName          GeoID       Date  NewCases  \
0           Aruba        NaN     Aruba__nan 2020-01-01       0.0   
1           Aruba        NaN     Aruba__nan 2020-01-02       0.0   
2           Aruba        NaN     Aruba__nan 2020-01-03       0.0   
3           Aruba        NaN     Aruba__nan 2020-01-04       0.0   
4           Aruba        NaN     Aruba__nan 2020-01-05       0.0   
...           ...        ...            ...        ...       ...   
98695    Zimbabwe        NaN  Zimbabwe__nan 2020-07-27     192.0   
98696    Zimbabwe        NaN  Zimbabwe__nan 2020-07-28     113.0   
98697    Zimbabwe        NaN  Zimbabwe__nan 2020-07-29      62.0   
98698    Zimbabwe        NaN  Zimbabwe__nan 2020-07-30     213.0   
98699    Zimbabwe        NaN  Zimbabwe__nan 2020-07-31      77.0   

       C1_School closing  C2_Workplace closing  C3_Cancel public events  \
0                    0.0                   0.0                      0.0   
1                    0.0                   0.0                      0.0   
2                    0.0                   0.0                      0.0   
3                    0.0                   0.0                      0.0   
4                    0.0                   0.0                      0.0   
...                  ...                   ...                      ...   
98695                3.0                   1.0                      2.0   
98696                3.0                   1.0                      2.0   
98697                3.0                   1.0                      2.0   
98698                3.0                   1.0                      2.0   
98699                3.0                   1.0                      2.0   

       C4_Restrictions on gatherings  C5_Close public transport  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        0.0   
3                                0.0                        0.0   
4                                0.0                        0.0   
...                              ...                        ...   
98695                            3.0                        1.0   
98696                            3.0                        1.0   
98697                            3.0                        1.0   
98698                            3.0                        1.0   
98699                            3.0                        1.0   

       C6_Stay at home requirements  C7_Restrictions on internal movement  \
0                               0.0                                   0.0   
1                               0.0                                   0.0   
2                               0.0                                   0.0   
3                               0.0                                   0.0   
4                               0.0                                   0.0   
...                             ...                                   ...   
98695                           2.0                                   2.0   
98696                           2.0                                   2.0   
98697                           2.0                                   2.0   
98698                           2.0                                   2.0   
98699                           2.0                                   2.0   

       C8_International travel controls  H1_Public information campaigns  \
0                                   0.0                              0.0   
1                                   0.0                              0.0   
2                                   0.0                              0.0   
3                                   0.0                              0.0   
4                                   0.0                              0.0   
...                                 ...                              ...   
98695                     

In [13]:
# Set number of past days to use to make predictions
nb_lookback_days = 30

# Create training data across all countries for predicting one day ahead
X_cols = cases_col + npi_cols
y_col = cases_col
X_samples = []
y_samples = []
geo_ids = df.GeoID.unique()
for g in geo_ids:
    gdf = df[df.GeoID == g]
    all_case_data = np.array(gdf[cases_col])
    all_npi_data = np.array(gdf[npi_cols])

    # Create one sample for each day where we have enough data
    # Each sample consists of cases and npis for previous nb_lookback_days
    nb_total_days = len(gdf)
    for d in range(nb_lookback_days, nb_total_days - 1):
        X_cases = all_case_data[d-nb_lookback_days:d]

        # Take negative of npis to support positive
        # weight constraint in Lasso.
        X_npis = -all_npi_data[d - nb_lookback_days:d]

        # Flatten all input data so it fits Lasso input format.
        X_sample = np.concatenate([X_cases.flatten(),
                                   X_npis.flatten()])
        y_sample = all_case_data[d + 1]
        X_samples.append(X_sample)
        y_samples.append(y_sample)

X_samples = np.array(X_samples)
y_samples = np.array(y_samples).flatten()

In [14]:
# Helpful function to compute mae
def mae(pred, true):
    return np.mean(np.abs(pred - true))

In [15]:
print( X_samples )

[[ 0.  0.  0. ... -0. -0. -0.]
 [ 0.  0.  0. ... -0. -0. -0.]
 [ 0.  0.  0. ... -0. -0. -0.]
 ...
 [ 0.  7. 17. ... -1. -1. -4.]
 [ 7. 17. 14. ... -1. -1. -4.]
 [17. 14. 12. ... -1. -1. -4.]]


In [16]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_samples,
                                                    y_samples,
                                                    test_size=0.2,
                                                    random_state=301)

In [17]:
# Create and train Lasso model.
# Set positive=True to enforce assumption that cases are positively correlated
# with future cases and npis are negatively correlated.
model = Lasso(alpha=0.1,
              precompute=True,
              max_iter=10000,
              positive=True,
              selection='random')
# Fit model
model.fit(X_train, y_train)

Lasso(alpha=0.1, max_iter=10000, positive=True, precompute=True,
      selection='random')

In [18]:
# Evaluate model
train_preds = model.predict(X_train)
train_preds = np.maximum(train_preds, 0) # Don't predict negative cases
print('Train MAE:', mae(train_preds, y_train))

test_preds = model.predict(X_test)
test_preds = np.maximum(test_preds, 0) # Don't predict negative cases
print('Test MAE:', mae(test_preds, y_test))

Train MAE: 137.89045491775633
Test MAE: 144.29998061201297


In [19]:
# Inspect the learned feature coefficients for the model
# to see what features it's paying attention to.

# Give names to the features
x_col_names = []
for d in range(-nb_lookback_days, 0):
    x_col_names.append('Day ' + str(d) + ' ' + cases_col[0])
for d in range(-nb_lookback_days, 1):
    for col_name in npi_cols:
        x_col_names.append('Day ' + str(d) + ' ' + col_name)

# View non-zero coefficients
for (col, coeff) in zip(x_col_names, list(model.coef_)):
    if coeff != 0.:
        print(col, coeff)
print('Intercept', model.intercept_)

Day -13 NewCases 0.011888754283417078
Day -7 NewCases 0.0075212196320592175
Day -6 NewCases 0.3534078163466619
Day -5 NewCases 0.27196253262922865
Day -4 NewCases 0.04823340556940747
Day -3 NewCases 0.043098078926488224
Day -2 NewCases 0.09954190100093144
Day -1 NewCases 0.22722281516301723
Day -28 C2_Workplace closing 7.396920149013801
Day -26 C6_Stay at home requirements 8.426057171879076
Day -21 C2_Workplace closing 1.3308817435018623
Day -17 C2_Workplace closing 3.627934267352775
Intercept 27.60996511177774


In [20]:
# Save model to file
if not os.path.exists('models'):
    os.mkdir('models')
with open('models/model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

## Evaluation

Now that the predictor has been trained and saved, this section contains the functionality for evaluating it on sample evaluation data.

In [21]:
# Reload the module to get the latest changes
import predict
from importlib import reload
reload(predict)
from predict import predict_df

In [22]:
%%time
path = os.path.abspath("../../../covid_xprize/validation/data/2020-09-30_historical_ip.csv")  
preds_df = predict_df("2020-08-01", "2020-08-31", path_to_ips_file=path, verbose=True)


Predicting for Aruba__nan
2020-08-01: 64.74624899215466
2020-08-02: 82.38619577104078
2020-08-03: 98.58901922816806
2020-08-04: 104.9637973327561
2020-08-05: 103.89808732042944
2020-08-06: 117.07860244830464
2020-08-07: 148.4843232865083
2020-08-08: 168.2264970225953
2020-08-09: 183.97156320641037
2020-08-10: 193.77879061846176
2020-08-11: 203.24364204212497
2020-08-12: 221.08557888583408
2020-08-13: 243.61722889397475
2020-08-14: 263.6589751959551
2020-08-15: 280.2710657864535
2020-08-16: 294.22344278468455
2020-08-17: 309.3447205049069
2020-08-18: 328.3438585980769
2020-08-19: 349.2730336610113
2020-08-20: 369.3881151522304
2020-08-21: 387.64104221562
2020-08-22: 404.9646499882851
2020-08-23: 423.3268727944187
2020-08-24: 447.2410839508505
2020-08-25: 469.3518616027157
2020-08-26: 490.88157938346956
2020-08-27: 503.01650391766674
2020-08-28: 522.8051386472541
2020-08-29: 543.7931625152971
2020-08-30: 566.8760139463297
2020-08-31: 589.7234514435318

Predicting for Afghanistan__nan
20

In [23]:
# Check the predictions
preds_df.head()

CountryName RegionName       Date  PredictedDailyNewCases
213       Aruba        NaN 2020-08-01               64.746249
214       Aruba        NaN 2020-08-02               82.386196
215       Aruba        NaN 2020-08-03               98.589019
216       Aruba        NaN 2020-08-04              104.963797
217       Aruba        NaN 2020-08-05              103.898087

# Validation
This is how the predictor is going to be called during the competition.  
!!! PLEASE DO NOT CHANGE THE API !!!

In [24]:
!python predict.py -s 2020-08-01 -e 2020-08-04 -ip ../../../covid_xprize/validation/data/2020-09-30_historical_ip.csv -o predictions/2020-08-01_2020-08-04.csv

Generating predictions from 2020-08-01 to 2020-08-04...
Saved predictions to predictions/2020-08-01_2020-08-04.csv
Done!


In [25]:
!head predictions/2020-08-01_2020-08-04.csv

CountryName,RegionName,Date,PredictedDailyNewCases
Aruba,,2020-08-01,64.74624899215466
Aruba,,2020-08-02,82.38619577104078
Aruba,,2020-08-03,98.58901922816806
Aruba,,2020-08-04,104.9637973327561
Afghanistan,,2020-08-01,259.60476285571406
Afghanistan,,2020-08-02,271.11709295958445
Afghanistan,,2020-08-03,298.08190747964414
Afghanistan,,2020-08-04,298.96785358754033
Angola,,2020-08-01,105.67447491172274


# Test cases
We can generate a prediction file. Let's validate a few cases...

In [2]:
import os, sys
print(sys.path)
from AlphanumericsTeam.data.augment import applyFunc
from covid_xprize.validation.predictor_validation import validate_submission

def validate(start_date, end_date, ip_file, output_file):
    # First, delete any potential old file
    try:
        os.remove(output_file)
    except OSError:
        pass
    
    # Then generate the prediction, calling the official API
    !python predict.py -s {start_date} -e {end_date} -ip {ip_file} -o {output_file}
    
    # And validate it
    errors = validate_submission(start_date, end_date, ip_file, output_file)
    if errors:
        for error in errors:
            print(error)
    else:
        print("All good!")

['/home/sid/git/covid-xprize/AlphanumericsTeam/predictors/linear', '/home/sid/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/vscode_datascience_helpers/../.does-not-exist', '/home/sid', '/home/sid/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles', '/home/sid/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/lib/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '', '/home/sid/git/covid-xprize/venv/lib/python3.7/site-packages', '/home/sid/git/covid-xprize/venv/lib/python3.7/site-packages/IPython/extensions', '/home/sid/.ipython']


ModuleNotFoundError: No module named 'AlphanumericsTeam'

## 4 days, no gap
- All countries and regions
- Official number of cases is known up to start_date
- Intervention Plans are the official ones

In [ ]:
validate(start_date="2020-08-01",
         end_date="2020-08-04",
         ip_file="../../../validation/data/2020-09-30_historical_ip.csv",
         output_file="predictions/val_4_days.csv")

## 1 month in the future
- 2 countries only
- there's a gap between date of last known number of cases and start_date
- For future dates, Intervention Plans contains scenarios for which predictions are requested to answer the question: what will happen if we apply these plans?

In [ ]:
%%time
validate(start_date="2021-01-01",
         end_date="2021-01-31",
         ip_file="../../../validation/data/future_ip.csv",
         output_file="predictions/val_1_month_future.csv")

## 180 days, from a future date, all countries and regions
- Prediction start date is 1 week from now. (i.e. assuming submission date is 1 week from now)  
- Prediction end date is 6 months after start date.  
- Prediction is requested for all available countries and regions.  
- Intervention plan scenario: freeze last known intervention plans for each country and region.  

As the number of cases is not known yet between today and start date, but the model relies on them, the model has to predict them in order to use them.  
This test is the most demanding test. It should take less than 1 hour to generate the prediction file.

### Generate the scenario

In [ ]:
from datetime import datetime, timedelta

start_date = datetime.now() + timedelta(days=7)
start_date_str = start_date.strftime('%Y-%m-%d')
end_date = start_date + timedelta(days=180)
end_date_str = end_date.strftime('%Y-%m-%d')
print(f"Start date: {start_date_str}")
print(f"End date: {end_date_str}")

In [ ]:
from covid_xprize.validation.scenario_generator import get_raw_data, generate_scenario, NPI_COLUMNS
DATA_FILE = 'data/OxCGRT_latest.csv'
latest_df = get_raw_data(DATA_FILE, latest=True)
scenario_df = generate_scenario(start_date_str, end_date_str, latest_df, countries=None, scenario="Freeze")
scenario_file = "predictions/180_days_future_scenario.csv"
scenario_df.to_csv(scenario_file, index=False)
print(f"Saved scenario to {scenario_file}")

### Check it

In [ ]:
%%time
validate(start_date=start_date_str,
         end_date=end_date_str,
         ip_file=scenario_file,
         output_file="predictions/val_6_month_future.csv")